// <auto-generated />
using System;
using ItemzApp.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ItemzApp.API.Migrations
{
    [DbContext(typeof(ItemzContext))]
    [Migration("20200625151413_AutoGenerateProjectGuid")]
    partial class AutoGenerateProjectGuid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ItemzApp.API.Entities.Itemz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1028)")
                        .HasMaxLength(1028);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("Itemzs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9153a516-d69e-4364-b17e-03b87442e21c"),
                            CreatedBy = "User 1",
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "Requirements to be described here.",
                            Name = "Item 1",
                            Priority = "High",
                            Status = "New"
                        },
                        new
                        {
                            Id = new Guid("5e76f8e8-d3e7-41db-b084-f64c107c6783"),
                            CreatedBy = "User 2",
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "Requirements to be described here.",
                            Name = "Item 2",
                            Priority = "Medium",
                            Status = "New"
                        },
                        new
                        {
                            Id = new Guid("0fa2f0eb-ed40-4265-8c0c-c24bbc84799f"),
                            CreatedBy = "User 3",
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "Requirements to be described here.",
                            Name = "Item 3",
                            Priority = "Low",
                            Status = "New"
                        },
                        new
                        {
                            Id = new Guid("853c9a62-1f5f-4368-8bc9-f94c68d29fce"),
                            CreatedBy = "User 4",
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "Requirements to be described here.",
                            Name = "Item 4",
                            Priority = "Low",
                            Status = "New"
                        },
                        new
                        {
                            Id = new Guid("04f4d829-d230-4b76-bf95-4d2bed426f6b"),
                            CreatedBy = "User 5",
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "Requirements to be described here.",
                            Name = "Item 5",
                            Priority = "Low",
                            Status = "New"
                        });
                });

            modelBuilder.Entity("ItemzApp.API.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1028)")
                        .HasMaxLength(1028);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42f62a6c-fcda-4dac-a06c-406ac1c17770"),
                            CreatedBy = "User 1",
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "This is Project 1",
                            Name = "Project 1",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("b69cf0d7-70ad-4f73-aa4a-8daad5181e1e"),
                            CreatedBy = "User 1",
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "This is Project 2",
                            Name = "Project 2",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("ItemzApp.API.Entities.ProjectJoinItemz", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemzId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProjectId", "ItemzId");

                    b.HasIndex("ItemzId");

                    b.ToTable("ProjectJoinItemz");

                    b.HasData(
                        new
                        {
                            ProjectId = new Guid("42f62a6c-fcda-4dac-a06c-406ac1c17770"),
                            ItemzId = new Guid("9153a516-d69e-4364-b17e-03b87442e21c")
                        },
                        new
                        {
                            ProjectId = new Guid("b69cf0d7-70ad-4f73-aa4a-8daad5181e1e"),
                            ItemzId = new Guid("5e76f8e8-d3e7-41db-b084-f64c107c6783")
                        });
                });

            modelBuilder.Entity("ItemzApp.API.Entities.ProjectJoinItemz", b =>
                {
                    b.HasOne("ItemzApp.API.Entities.Itemz", "Itemz")
                        .WithMany("ProjectJoinItemz")
                        .HasForeignKey("ItemzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItemzApp.API.Entities.Project", "Project")
                        .WithMany("ProjectJoinItemz")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
